# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fintech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_encrypted', models.BooleanField()),
                ('upload', models.FileField(upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=30)),
                ('company_ceo', models.CharField(max_length=30)),
                ('company_phone', models.CharField(max_length=30)),
                ('company_location', models.CharField(max_length=30)),
                ('company_country', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('current_projects', models.TextField()),
                ('is_private', models.BooleanField()),
                ('has_attachments', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fintech.Report'),
        ),
    ]
