# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('Fintech', '0003_auto_20170417_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_groups', models.ManyToManyField(to='auth.Group')),
                ('allowed_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Fintech.Report')),
            ],
        ),
    ]
