# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fintech', '0004_reportpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpermissions',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='reportpermissions',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
