# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 19:22
from __future__ import unicode_literals

import Fintech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fintech', '0006_message_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypt',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to=Fintech.models.generate_file_path),
        ),
    ]
