# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fintech', '0007_auto_20170423_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='type',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='key',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
