# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fintech', '0008_auto_20170423_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='static_encrypt',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
