# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fintech', '0010_companydetails_company_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='industry',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='sector',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
